micronaut:
  application:
    name: offers
redis:
  uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"
consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
  health:
    enabled: true
offers:
  api:
    version: v1