name: Corretto CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - run: wget https://corretto.aws/downloads/latest/amazon-corretto-${{ matrix.java }}-x64-linux-jdk.tar.gz --output-document jdk.tar.gz
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        jdkFile: jdk.tar.gz
    - run: java -version
    - name: Build with Gradle
      run: ./gradlew check --no-daemon --parallel --continue