name: Corretto CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11']
    container: amazoncorretto:${{ matrix.java }}
    steps:
    - name: Display Java and Linux version
      run: java -version && cat /etc/system-release
    - name: Install tar && gzip
      run: yum install -y tar gzip
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - name: Build with Gradle
      run: unset HOSTNAME ; LANG=en_US.utf-8 LC_ALL=en_US.utf-8 ./gradlew check --no-daemon --parallel --continue
