name: Corretto CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: amazoncorretto:8
    steps:
    - run: yum install -y tar
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - run: java -version
    - name: Build with Gradle
      run: ./gradlew check --no-daemon --parallel --continue
