name: Corretto CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        java: ['8', '11']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - uses: alvarosanchez/corretto-amazon-linux-action@master
      with:
        corretto-version: ${{ matrix.java }}
        command: "./gradlew check --no-daemon --parallel --continue"

  build_container:
    container: amazoncorretto:8
    steps:
    - run: java -version
    - run: ./gradlew tasks